;;; my-appearance.el --- Aspetto: temi, caratteri, spaziatura -*- lexical-binding: t -*-

;;; Commentary:

;; Tema (compresi i temi personali sotto themes/), tipografia e
;; spaziatura della cornice.
;;
;; L'ordine interno di questo file conta: custom-theme-load-path prima
;; della dichiarazione del pacchetto, la dichiarazione prima di ogni
;; load-theme, e spacious-padding dopo il caricamento del tema.

;;; Code:
;; Personal themes live in the repository, under themes/, so that they
;; are tracked by git.  This MUST come before the modus-themes package
;; declaration: the manual warns that customizing custom-theme-load-path
;; afterwards breaks the loading of theme files.
(add-to-list 'custom-theme-load-path
             (expand-file-name "themes/" user-emacs-directory))

;; modus-themes from GNU ELPA, installed on top of the copy bundled with
;; Emacs 30 (version 4.x).  Reference version: 5.3.0.  Version 5 is what
;; brings the palette machinery we are after: semantic mappings, palette
;; overrides and derivative themes.
;;
;; This declaration MUST come before any `load-theme' call, and it is the
;; whole point of the block.  Both copies sit on disk at once: the built-in
;; themes are not in the `load-path' and are reached through `require-theme',
;; while the ELPA copy is an ordinary package reached through `require'.
;; Declaring the package is what makes the ELPA one win.
;;
;; :demand t defeats use-package's lazy loading on purpose -- the theme has to
;; be in place at startup, not on first use.  :ensure is implicit here, since
;; use-package-always-ensure is set further up.
;;
;; Cost: the package is loaded at every startup, but this is not new -- a
;; theme file pulls it in anyway.  What changes is only which copy is loaded.
;;
;; Graceful degradation is left to the block below, which keeps using plain
;; `load-theme': that works on both 4.x and 5.x, so on a machine where this
;; package fails to install, Emacs falls back to the bundled themes.

(use-package modus-themes
  :demand t)

;;; ---

;; Piccole rifiniture estetiche dei temi modus: corsivo per commenti e costrutti "doc", grassetto per le parole chiave.
;; Vanno valutate PRIMA del caricamento del tema; cambiandole a Emacs avviato, il tema va ricaricato.
;; Nota: dalla versione 5 queste due opzioni governano molte più facce di prima (diverse facce che erano incondizionatamente in grassetto o corsivo ora dipendono da qui). Aspettati quindi più grassetti e corsivi rispetto alla 4.x: se non piacciono, la leva è questa.

;; Mixed fonts and a proportional user interface.  Both options are read at the
;; same moment as the two above, so they belong in the same block:
;; - `modus-themes-mixed-fonts' makes spacing-sensitive faces (Org tables, code
;;   blocks, verbatim text) inherit from `fixed-pitch' unconditionally.  It is
;;   the precondition that makes `variable-pitch-mode' safe in prose buffers;
;;   see the typography section below.
;; - `modus-themes-variable-pitch-ui' switches the mode line (active and
;;   inactive), the header line and the tab bar / tab line to `variable-pitch'.
;;   The minibuffer is NOT affected: vertico and marginalia keep their
;;   character-based alignment.
;; Both work through faces generated by the modus machinery, so they reach the
;; derivative themes under themes/ only insofar as those are built with it.

(setq modus-themes-italic-constructs t
      modus-themes-bold-constructs t
      modus-themes-mixed-fonts t
      modus-themes-variable-pitch-ui t)

;;; ---

;; Tema che segue automaticamente l'aspetto di sistema chiaro/scuro.
;; L'hook ns-system-appearance-change-functions è una funzionalità esclusiva di Emacs Plus: se la build in uso non ce l'ha (Emacs vanilla, terminale...), si ripiega su un tema fisso.
;; La funzione è idempotente (disattiva prima i temi attivi), quindi un'eventuale doppia chiamata all'avvio è innocua.
;; Nota: si usa load-theme e non modus-themes-load-theme (comodo, perché disattiva da sé i temi attivi) perché quest'ultimo esiste solo nella 5.x: load-theme mantiene il file funzionante anche dove il pacchetto non è installato.
;; Nota sulla barra del titolo trasparente (early-init.el): con ns-appearance a nil (il default), macOS fa seguire alla finestra l'aspetto di sistema. Poiché anche il tema segue l'aspetto di sistema, barra e tema restano sincronizzati PER COSTRUZIONE: nessun intervento necessario. Servirebbe impostare ns-appearance solo adottando un tema fisso scollegato dal sistema.

;; Attenzione a non aggiungere un load-theme fuori dall'`if' qui sotto: verrebbe
;; eseguito SEMPRE, anche dopo il ramo scuro, e sovrapporrebbe il tema chiaro a
;; quello appena caricato senza disattivarlo. Il sintomo è insidioso, perché il
;; difetto colpisce solo l'AVVIO: cambiando aspetto a Emacs già aperto scatta
;; l'hook, che chiama my/apply-theme da sola e ripulisce tutto.
;; Controllo rapido: C-h v custom-enabled-themes deve elencare UN SOLO tema.

(defun my/apply-theme (appearance)
  "Carica il tema adatto ad APPEARANCE (`light' o `dark')."
  (mapc #'disable-theme custom-enabled-themes)  ; evita temi sovrapposti
  (pcase appearance
    ('light (load-theme 'chaun-bay t))
    ('dark  (load-theme 'chaun-bay-dark t))))

(if (boundp 'ns-system-appearance-change-functions)
    (progn
      (add-hook 'ns-system-appearance-change-functions #'my/apply-theme)
      ;; Applica il tema già all'avvio (fallback su 'light se la variabile non è ancora valorizzata, es. avvio come daemon).
      (my/apply-theme (or (and (boundp 'ns-system-appearance)
                               ns-system-appearance)
                          'light)))
  (load-theme 'chaun-bay t))

;;; --- Aspetto: caratteri e tipografia ---

;; Three faces carry the whole typography (see Info node `(emacs) Faces'):
;; - `default': the base typeface, inherited by every face that does not specify
;;   one of its own.  Its height is in tenths of a point, so 140 = 14 pt (the
;;   macOS default is Menlo 12);
;; - `fixed-pitch': monospaced, inherited by whatever must stay aligned -- Org
;;   tables, code blocks, verbatim text -- even inside a proportional buffer;
;; - `variable-pitch': proportional, used for prose and for the UI elements
;;   listed in the modus block above.
;; The height of the latter two is a FLOAT, i.e. a multiplier relative to
;; `default': changing the 140 rescales all three together.
;;
;; The modus themes never set `fixed-pitch' and `variable-pitch' themselves --
;; they route through intermediary faces that inherit from these -- so the theme
;; reload on every light/dark switch does not undo what is set here.
;;
;; Note: changing the font makes the frame resize itself to keep the same number
;; of columns and rows.

(defun my/first-available-font (families)
  "Return the first family in FAMILIES installed on this system, or nil."
  (seq-find (lambda (family) (member family (font-family-list))) families))

;; JetBrains Mono and IBM Plex Sans are open source (OFL licence).  The
;; fallbacks -- Menlo and Helvetica Neue, proprietary Apple fonts preinstalled
;; on macOS -- are here only so the configuration degrades gracefully on a
;; machine where the intended fonts are missing.

(let ((mono (my/first-available-font '("JetBrains Mono" "Menlo")))
      (prop (my/first-available-font '("IBM Plex Sans" "Helvetica Neue"))))
  (when mono
    (set-face-attribute 'default     nil :family mono :height 140)
    (set-face-attribute 'fixed-pitch nil :family mono :height 1.0))
  (when prop
    (set-face-attribute 'variable-pitch nil :family prop :height 1.1)))

;;; ---

;; Interlinea leggermente aumentata (2 pixel extra tra le righe)
;; Stile app MacOS.

(setq-default line-spacing 2)

;;; ---

;; Proportional font in text buffers: text-mode and every mode derived from it
;; (Org, Markdown...), the same reach as `visual-line-mode'.  Thanks to
;; `modus-themes-mixed-fonts' above, tables and code stay monospaced.
;; To try it on a single buffer without touching this file: M-x variable-pitch-mode

(defun my/enable-variable-pitch ()
  "Enable `variable-pitch-mode', except in Git commit message buffers.
Git commit conventions are counted in characters -- about 50 for the
summary line, 72 for the body -- so those buffers must stay monospaced.
Magit binds `git-commit-mode' to t while the major mode hook runs,
precisely so that hooks like this one can detect the situation."
  (unless (bound-and-true-p git-commit-mode)
    (variable-pitch-mode 1)))

(add-hook 'text-mode-hook #'my/enable-variable-pitch)

;;; --- Aspetto: spaziatura di finestre e riquadri ---

;; spacious-padding (GNU ELPA): visual-only tweaks to frame parameters
;; and faces.  No command or key binding is affected.
;;
;; What it buys us: side-by-side windows are separated by a band of
;; background colour instead of a 1 px line, so each pane reads as a
;; distinct surface.  Mode line and fringes gain some breathing room.
;;
;; Placement matters: this block must come AFTER the theme is loaded,
;; because the mode reads the background of the `default' face in order
;; to paint the dividers with it.
;;
;; Reversible at any time with M-x spacious-padding-mode: the mode stores
;; the original frame parameters and restores them when disabled.  One
;; exception, the scroll bar; see below.
(use-package spacious-padding
  :custom
  ;; The plist below carries the upstream defaults, kept for visibility.
  ;; Three values differ from them and are marked CHANGED inline.
  ;;
  ;; 1. :internal-border-width is the space between the frame edge and
  ;;    its contents, on all four sides -- below the minibuffer included.
  ;;    Set to 12 to match the dividers, so the frame keeps one uniform
  ;;    margin all around.
  ;;    MUST be kept in sync with early-init.el, which paints the first
  ;;    frame before this file is read: a mismatch shows up as the margin
  ;;    visibly jumping at startup.
  ;;
  ;; 2. :right-divider-width is lowered from the upstream 30, which is
  ;;    too much here because the divider is not the whole gutter: two
  ;;    side-by-side windows are already separated by a fringe, the
  ;;    scroll bar and another fringe.
  ;;    Never set it below 2: the package hides the `vertical-border'
  ;;    face unconditionally, but paints the divider only when its width
  ;;    is greater than 1.  Below that, windows would end up with no
  ;;    visible separation at all.
  ;;
  ;; 3. :scroll-bar-width must match the native macOS scroll bar width or
  ;;    the bar gets clipped; the upstream default of 8 targets the thin
  ;;    GTK bar.  Measure it with M-: (frame-scroll-bar-width) after
  ;;    setting that frame parameter to nil.  Two caveats: nil is not
  ;;    usable in this plist (the package falls back to a hardcoded 8),
  ;;    and turning the mode off does not restore the native width
  ;;    either -- that takes a restart.
  (spacious-padding-widths
   '( :internal-border-width 14   ; CHANGED - margin around the frame
      :header-line-width 4
      :mode-line-width 6
      :custom-button-width 3
      :tab-width 4
      :right-divider-width 12     ; CHANGED - gap between side-by-side windows
      :scroll-bar-width 17        ; CHANGED - native macOS width
      :fringe-width 8))
  :init
  (spacious-padding-mode 1)
  :config
  ;; The package handles the right divider only: it has no
  ;; :bottom-divider-width key, so windows stacked with C-x 2 would get
  ;; no gap at all, with the mode line as their only separator.  We set
  ;; that frame parameter ourselves, at the same 12 px as everything
  ;; else.  It reads as empty space because the package already paints
  ;; the `window-divider' face with the background colour, and that face
  ;; covers the bottom divider too.
  ;;
  ;; Kept inside :config on purpose: without spacious-padding the divider
  ;; would show up as a visible grey bar.
  ;;
  ;; Two calls because they cover different frames: default-frame-alist
  ;; applies to frames created later, modify-all-frames-parameters to the
  ;; one already open at startup.
  (let ((width 12))
    (add-to-list 'default-frame-alist `(bottom-divider-width . ,width))
    (modify-all-frames-parameters `((bottom-divider-width . ,width)))))


(provide 'my-appearance)
;;; my-appearance.el ends here
